#### Improvements 
- Building neural networks using nn module
- Using built-in activation function
- Using built-in loss function
- Using built-in optimizer

In [2]:
import torch
import torch.nn as nn


- The torch.nn module in pytorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively.It abstracts the complexity of creating and training neural networks by offering pre-built layers,loss functions,activation functions and other utilities,enabling you to focus on designing and experimenting with model architectures

- nn.module: The base class for all neural network modules.Your custom models and layers should subclass this class

####  Key components of nn module



- Layers                .... nn.Linear,nn.LSTM,nn.Conv2d
- Activation functions        ... nn.ReLU
- Loss functions                .... nn.CrossEntropyLoss
- Container modules             ....a sequential container to stack layers in order (eg, nn.sequential)
- Regularization and dropout     .... nn.BatchNorm2d,nn.Dropout

#### Calling the Object Triggers `__call__`:

- In PyTorch, `nn.Linear` inherits from `nn.Module`, which defines a `__call__` method.

- When you do `self.linear(features)`, it calls `self.linear.__call__(features)` internally.

- The `__call__` method, in turn, invokes the `forward` method of the `nn.Linear` class.


In [12]:
class Model(nn.Module):

    def __init__(self,n_features):

        # Invoking the parent class constructor in the child class constructor
        super().__init__()

        self.layer1 = nn.Linear(n_features,3)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        z1 = self.layer1(features)
        out1 = self.relu(z1)

        z2 = self.layer2(out1)
        out2 = self.sigmoid(z2)

        return out2



In [13]:
# create dataset

features = torch.rand(10,5)

# create a model

model = Model(features.shape[1])
model(features),model(features).shape

(tensor([[0.3814],
         [0.3856],
         [0.3810],
         [0.3942],
         [0.3867],
         [0.4209],
         [0.3799],
         [0.4012],
         [0.3916],
         [0.4053]], grad_fn=<SigmoidBackward0>),
 torch.Size([10, 1]))

In [14]:
model.layer1.weight,model.layer1.bias

(Parameter containing:
 tensor([[-0.2294,  0.3971,  0.4454, -0.3045,  0.3953],
         [ 0.2464,  0.0275, -0.0132,  0.2077,  0.1958],
         [ 0.2679,  0.0267, -0.2227, -0.1950, -0.2872]], requires_grad=True),
 Parameter containing:
 tensor([0.3417, 0.0523, 0.0865], requires_grad=True))

In [15]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Simplifying further using nn.Sequential

In [28]:
class Model(nn.Module):

    def __init__(self,n_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(n_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
             nn.Sigmoid()
        )

    def forward(self,features):

        out = self.network(features)
        return out
    



# create dataset
features = torch.rand(10,5)

# create a model
model = Model(features.shape[1])
model(features)

tensor([[0.4819],
        [0.5033],
        [0.4957],
        [0.4912],
        [0.4972],
        [0.4992],
        [0.5050],
        [0.5023],
        [0.5047],
        [0.4873]], grad_fn=<SigmoidBackward0>)