In [4]:
import torch

print(torch.__version__)

2.6.0+cpu


In [6]:
print(torch.cuda.is_available())

False


### Creating a tensor

In [18]:
print(torch.empty(2,3))
print(torch.zeros(2,3))
print(torch.ones(2,3))

tensor([[8.8036e+12, 1.0468e-42, 5.4558e-01],
        [1.5241e-01, 5.0594e-01, 7.6809e-01]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
# random values that lie b/w o and 1 (Normal distribution)
print(torch.rand(2,3))

# use of seed for reproduciblity
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [23]:
# custom tensor using an iterable like a python list!
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
# using arange
print(torch.arange(0,10,2))
print(torch.arange(0,10))

print("-------------------------------------------")


# using linspace
print(torch.linspace(0,10,10))
print(torch.linspace(0,10,4))

tensor([0, 2, 4, 6, 8])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
-------------------------------------------
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [47]:
# using eye (Identity matrix), specify the order
print(torch.eye(3))
print(torch.eye(1))
print(torch.eye(2))

print("-------------------------------------------")

# using full (constant matrix/uniform matrix)
print(torch.full((2,2),5))
print(torch.full((2,1),5))
print(torch.full((1,1),2))
print(torch.full((3,3),1))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1.]])
tensor([[1., 0.],
        [0., 1.]])
-------------------------------------------
tensor([[5, 5],
        [5, 5]])
tensor([[5],
        [5]])
tensor([[2]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### Tensor shapes

In [51]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape,type(x))

torch.Size([2, 3]) <class 'torch.Tensor'>


In [55]:
print(torch.empty_like(x))

print(torch.zeros_like(x))

print(torch.ones_like(x))


tensor([[1065353216,          0, 1065353216],
        [         0, 1065353216,          1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [74]:
try:
    print(torch.rand_like(x))
except RuntimeError as e:
    print(f"error:mismatch of datatype b/w rand_like() and x")

error:mismatch of datatype b/w rand_like() and x


### Tensor data types

In [71]:
print(x.dtype)
torch.tensor([1,2,3],dtype = torch.float32)

torch.int64


tensor([1., 2., 3.])

In [77]:
# solving the datatype mismatch error!
print(torch.rand_like(x,dtype = torch.float32))

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [ ]:
# converting a given tensor to another data type
print(x.to(torch.float32))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### Mathematical operations (tensors)

#### Scalar operation

In [82]:
x = torch.rand(2,2)
x

tensor([[0.0169, 0.2209],
        [0.9535, 0.7064]])

In [96]:
# addition
print(x+2)
print()

# substraction
print(x-2)
print()

# multiplication
print(x*2)
print()


# division
print(x/2)
print()

# integer division
print((x*100)//2)
print()

# mod
print(((x*100)//2)%2)
print()

# power
print(x**2)

tensor([[2.0169, 2.2209],
        [2.9535, 2.7064]])

tensor([[-1.9831, -1.7791],
        [-1.0465, -1.2936]])

tensor([[0.0338, 0.4418],
        [1.9071, 1.4128]])

tensor([[0.0084, 0.1104],
        [0.4768, 0.3532]])

tensor([[ 0., 11.],
        [47., 35.]])

tensor([[0., 1.],
        [1., 1.]])

tensor([[2.8558e-04, 4.8794e-02],
        [9.0923e-01, 4.9901e-01]])


#### Element wise operation(tensor)

In [117]:
a = torch.randn(2,3)
b = torch.rand(2,3)
a,b

(tensor([[-1.5916, -0.0928,  1.9353],
         [-0.3017,  0.9403, -2.1502]]),
 tensor([[0.5772, 0.3771, 0.2440],
         [0.8994, 0.1041, 0.9193]]))

In [121]:
# addition
print(a+b)

# substraction
print(a-b)

# multiplication
print(a*b)

#division
print(a/b)

tensor([[-1.0144,  0.2843,  2.1794],
        [ 0.5977,  1.0444, -1.2309]])
tensor([[-2.1688, -0.4700,  1.6913],
        [-1.2011,  0.8362, -3.0695]])
tensor([[-0.9186, -0.0350,  0.4722],
        [-0.2714,  0.0979, -1.9766]])
tensor([[-2.7574, -0.2461,  7.9315],
        [-0.3355,  9.0339, -2.3390]])


In [148]:
# Absolute value

c = torch.tensor([-1,-2,-3])
print(c,c.dtype,torch.absolute(c))
print()


# Round
d = torch.tensor([1.2,-2.5,3.2,-1,2.5])
print(d,d.dtype,torch.round(d))
print()

# ceil
print(torch.ceil(d))
print()

# floor
print(torch.floor(d))
print()

# clamp (clamp the values b/w 2 and 3)
# Those values less than 2 becomes 2 and greater than 3 becomes 3
print(torch.clamp(d,min=2,max=3))

tensor([-1, -2, -3]) torch.int64 tensor([1, 2, 3])

tensor([ 1.2000, -2.5000,  3.2000, -1.0000,  2.5000]) torch.float32 tensor([ 1., -2.,  3., -1.,  2.])

tensor([ 2., -2.,  4., -1.,  3.])

tensor([ 1., -3.,  3., -1.,  2.])

tensor([2.0000, 2.0000, 3.0000, 2.0000, 2.5000])


In [168]:
torch.manual_seed(100)

# sum
a = torch.randint(-1,5,(2,3))
print(a,a.shape,torch.sum(a),torch.sum(a).shape)

# sum along columns
print(torch.sum(a,dim=0),torch.sum(a,dim=0).shape)

# sum along rows
print(torch.sum(a,dim=1),torch.sum(a,dim=1).shape)


tensor([[3, 3, 4],
        [4, 0, 0]]) torch.Size([2, 3]) tensor(14) torch.Size([])
tensor([7, 3, 4]) torch.Size([3])
tensor([10,  4]) torch.Size([2])


In [194]:
# mean
print(torch.mean(a,dtype=float))
print(torch.mean(a,dim=0,dtype=float))
print(torch.mean(a,dim=1,dtype=float))
print()

# median
print(torch.median(a))

# standard deviation
print(torch.std(a.float()))
print()

# product 
print(f"product:{torch.prod(a)}")

# variance
print(f"variance:{torch.var(a.float())}")

# argmax
print(f"argmax:{torch.argmax(a),type(torch.argmax(a))}")

# argmin
print(torch.argmin(a))


tensor(2.3333, dtype=torch.float64)
tensor([3.5000, 1.5000, 2.0000], dtype=torch.float64)
tensor([3.3333, 1.3333], dtype=torch.float64)

tensor(3)
tensor(1.8619)

product:0
variance:3.4666666984558105
argmax:(tensor(2), <class 'torch.Tensor'>)
tensor(4)


#### Matrix operations

In [229]:
torch.manual_seed(100)
f = torch.randint(1,10,(2,2))
g = torch.randint(2,5,(2,2))

print(f)
print(g)

# Matrix multiplication
print(f"product of f and g:{torch.matmul(f,g)}")
print(f"inverse multiplication :{torch.matmul(g,f)}")
print()

# Dot product 
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([1,-1,2])
print(v1,v2)
print(f"dot product of v1 and v2:{torch.dot(v1,v2)}")
print(f"inverse:{torch.dot(v2,v1)}")


# Transpose
print(torch.transpose(f,dim0=0,dim1=1))
print(torch.transpose(f,1,0)) # only because it has 2 dimensions

# determinant
print(torch.det(g.float()))

tensor([[8, 8],
        [9, 9]])
tensor([[3, 3],
        [2, 3]])
product of f and g:tensor([[40, 48],
        [45, 54]])
inverse multiplication :tensor([[51, 51],
        [43, 43]])

tensor([1, 2, 3]) tensor([ 1, -1,  2])
dot product of v1 and v2:5
inverse:5
tensor([[8, 9],
        [8, 9]])
tensor([[8, 9],
        [8, 9]])
tensor(3.)


#### Comparison operations

In [236]:
torch.manual_seed(100)
i = torch.randint(10,(2,3))
j = torch.randint(10,(2,3))

print(i)
print(j)
print()

print(i>j)
print(j>i)
print(j==i)
print(i>=j)
print(j<=i)
print(j!=i)



tensor([[0, 2, 5],
        [9, 5, 1]])
tensor([[2, 8, 8],
        [0, 4, 3]])

tensor([[False, False, False],
        [ True,  True, False]])
tensor([[ True,  True,  True],
        [False, False,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [ True,  True, False]])
tensor([[False, False, False],
        [ True,  True, False]])
tensor([[True, True, True],
        [True, True, True]])


#### Some important functions on tensors

In [247]:
torch.manual_seed(20)
k = torch.randint(2,5,(2,3))

# Log
print(k)
print(torch.log(k))
print()

# sigmoid
print(torch.sigmoid(k))
print()

# softmax(along columns)
print(torch.softmax(k,dim=0,dtype=torch.float32))
print()

# relu
print(torch.relu(k))

tensor([[4, 3, 2],
        [3, 2, 4]])
tensor([[1.3863, 1.0986, 0.6931],
        [1.0986, 0.6931, 1.3863]])

tensor([[0.9820, 0.9526, 0.8808],
        [0.9526, 0.8808, 0.9820]])

tensor([[0.7311, 0.7311, 0.1192],
        [0.2689, 0.2689, 0.8808]])

tensor([[4, 3, 2],
        [3, 2, 4]])


### Inplace operations

In [272]:
torch.manual_seed(20)
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x),print(y)
print()

print(f"id of x:{id(x)}")
print(f"id of y:{id(y)}")
print()

print(f"inplace operation,id of x.add_(y): {id(x.add_(y))},(is same as the id of x because x gets modified in place)")
print(f"id of x+y: {id(x+y)}, a new memory space is created")
print()

print(f"id of torch.relu(x): {id(torch.relu(x))},a new memory address")
print(f"id of torch.relu_(x): {id(torch.relu_(x))}, is the same as id of x because x gets modified in place")


tensor([[0.5615, 0.1774, 0.8147],
        [0.3295, 0.2319, 0.7832]])
tensor([[0.8544, 0.1012, 0.1877],
        [0.9310, 0.0899, 0.3156]])

id of x:2048124187536
id of y:2048125585760

inplace operation,id of x.add_(y): 2048124187536,(is same as the id of x because x gets modified in place)
id of x+y: 2048129521600, a new memory space is created

id of torch.relu(x): 2048129521600,a new memory address
id of torch.relu_(x): 2048124187536, is the same as id of x because x gets modified in place


### Copying a tensor

In [277]:
torch.manual_seed(3)
x = torch.rand(2,3)

# Assignment operatior doesn't create a copy!
x = y
print(id(x),id(y),id(x) == id(y))


2048125585760 2048125585760 True


In [279]:
# Created the copy of the tensor in another memory location using clone()
x = y.clone()
print(id(x),id(y),id(x) == id(y))

2048125413696 2048125585760 False


### Device performance for tensor operations

In [2]:
import time
torch.manual_seed(20)

# create random matrices on cpu
size = 10_000
x = torch.randn(size,size)
y = torch.randn(size,size)

start = time.time()
result = torch.matmul(x,y)
end = time.time()

print(f"Total time taken on cpu: {end - start:.4f} seconds")



Total time taken on cpu: 3.1489 seconds


In [3]:
result.shape

torch.Size([10000, 10000])

### Reshaping the tensor

In [15]:
torch.manual_seed(2)
a = torch.ones(3,3)
print(a,a.ndim)

a = a.reshape(1,3,3)
print(a,a.ndim)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 2
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) 3


In [16]:
# flatten
a.flatten(),a.flatten().ndim,a.flatten().shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]), 1, torch.Size([9]))

In [18]:
# permute...permuting the order of the dimension of tensor!
a = torch.randn(2,3,4)
a.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [ ]:
# unsqueeze....utility....(providing a BATCH of input images to a CNN like n*226*226*3)
# A typical image size(example)

# unsqueeze ADDS  a new dimension at the specified dimension index

a = torch.rand(226,226,3)
a.unsqueeze(0).shape,a.unsqueeze(1).shape

(torch.Size([1, 226, 226, 3]), torch.Size([226, 1, 226, 3]))

In [33]:
# squeeze
# squeeze REMOVES  a dimension at the specified dimension index
d = torch.rand(1,20)
d.shape,d.squeeze(0).shape,d.squeeze(1).shape

(torch.Size([1, 20]), torch.Size([20]), torch.Size([1, 20]))

### Numpy vs Pytorch

In [38]:
import numpy as np

# converting a pytorch tensor to numpy array

x = torch.tensor([1,2,3])
print(x,type(x))


y = x.numpy()
y,type(y)

tensor([1, 2, 3]) <class 'torch.Tensor'>


(array([1, 2, 3]), numpy.ndarray)

In [41]:
# converting numpy array to pytorch tensor
c = np.array([1,2,3])
print(c,type(c))

d = torch.from_numpy(c)
print(d,type(d))

[1 2 3] <class 'numpy.ndarray'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
