In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[-1.28313158, -0.85825318, -1.29034374, ..., -0.96081578,
        -0.09675659, -0.12068258],
       [ 0.75121421, -0.12896842,  0.70823237, ...,  0.49816909,
        -0.14555523, -0.64574206],
       [-0.18820378, -1.96033527, -0.18610953, ..., -0.61849264,
        -0.30297021, -0.66625652],
       ...,
       [ 1.94788821,  1.33659107,  2.11727034, ...,  2.12450857,
         0.04176859,  0.82076513],
       [-0.49748909, -1.51996843, -0.56575537, ..., -1.33831537,
        -0.97985463, -0.75663107],
       [ 3.33822684, -0.44118617,  3.42178027, ...,  2.45038558,
         1.2396966 ,  0.23416226]], shape=(455, 30))

In [12]:
y_train

273    B
167    M
76     B
499    M
315    B
      ..
215    M
188    B
563    M
493    B
352    M
Name: diagnosis, Length: 455, dtype: object

#### Label Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,

#### Numpy arrays to pytorch tensors

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape,X_test_tensor.shape

(torch.Size([455, 30]), torch.Size([114, 30]))

In [18]:
y_train_tensor.shape,y_test_tensor.shape

(torch.Size([455]), torch.Size([114]))

In [32]:
X_train_tensor[0],X_train_tensor[0].shape,X_train_tensor[0].ndim

(tensor([-1.2831, -0.8583, -1.2903, -1.0576, -0.4338, -1.0795, -0.9760, -0.9026,
          0.9616,  0.0568, -0.4857,  0.3375, -0.5462, -0.5127,  2.2468, -0.8144,
         -0.7946, -0.3736, -0.3092,  0.1613, -1.1816, -0.7932, -1.2025, -0.9524,
          0.6467, -1.0026, -1.1257, -0.9608, -0.0968, -0.1207],
        dtype=torch.float64),
 torch.Size([30]),
 1)

In [34]:
y_train_tensor[0],y_train_tensor[0].shape,y_train_tensor[0].ndim

(tensor(0), torch.Size([]), 0)

In [60]:
X_train_tensor.shape,X_train_tensor.shape[1]

(torch.Size([455, 30]), 30)

### Defining the model

In [54]:
class MyNN:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss


##### Important hyperparameters

In [78]:
learning_rate = 0.01
epochs = 25

##### Training pipeline

In [81]:
# create the model instance
model = MyNN(X_train_tensor)

# Define loop

for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)


    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)
    

    # backward pass
    loss.backward()

    # parameters(trainable) update
    # During weights' update , we don't need to track the gradients
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    # zero gradients(to prevent accumulation of gradients)
    model.weights.grad.zero_()
    model.weights.grad.zero_()


    # print loss in each epoch
    print(f"Epoch {epoch + 1}, loss: {loss.item()}")


Epoch 1, loss: 3.5709709123925704
Epoch 2, loss: 3.5580509282179875
Epoch 3, loss: 3.54514053903527
Epoch 4, loss: 3.5322399369195367
Epoch 5, loss: 3.51934931731922
Epoch 6, loss: 3.50646887900508
Epoch 7, loss: 3.4935780348832615
Epoch 8, loss: 3.4804982809921805
Epoch 9, loss: 3.467429833215738
Epoch 10, loss: 3.454372900548951
Epoch 11, loss: 3.4413276945169744
Epoch 12, loss: 3.4282944290445974
Epoch 13, loss: 3.415273320378298
Epoch 14, loss: 3.402264586955267
Epoch 15, loss: 3.3892684493006513
Epoch 16, loss: 3.3762851299096366
Epoch 17, loss: 3.3633148531199657
Epoch 18, loss: 3.3503578449865583
Epoch 19, loss: 3.337359804976311
Epoch 20, loss: 3.324232990365732
Epoch 21, loss: 3.31112043339659
Epoch 22, loss: 3.2980223575950456
Epoch 23, loss: 3.284938987117219
Epoch 24, loss: 3.271870546650704
Epoch 25, loss: 3.2588172612792485


In [86]:
model.weights.shape

torch.Size([30, 1])

In [87]:
model.weights

tensor([[0.3348],
        [0.4678],
        [0.1111],
        [0.8458],
        [0.4072],
        [0.3937],
        [0.6572],
        [0.0261],
        [0.8801],
        [0.7946],
        [0.2828],
        [0.0316],
        [0.2839],
        [0.2370],
        [0.3112],
        [0.7997],
        [0.0449],
        [0.5015],
        [0.7337],
        [0.6357],
        [0.9148],
        [0.7320],
        [0.5581],
        [0.4443],
        [0.2479],
        [0.3308],
        [0.3874],
        [0.2164],
        [0.6453],
        [0.3429]], dtype=torch.float64, requires_grad=True)

In [88]:
model.bias

tensor([0.0254], dtype=torch.float64, requires_grad=True)

#### Evaluation

In [106]:

# Since this is for inference,
# We don't keep track of gradients here (weights are involved in this calculation, that's why switching off gradient tracking)
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()

    
accuracy = (y_pred==y_test_tensor).float().mean()
print(f"accuracy:{accuracy}")

    

accuracy:0.5438596606254578
