In [130]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [131]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [132]:
df.shape

(569, 33)

In [133]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [134]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train test split

In [135]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [136]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [137]:
X_train

array([[-0.61735712,  2.09876336, -0.6459163 , ..., -0.91596536,
        -0.78684962, -0.94627987],
       [ 2.2739799 ,  0.08959748,  2.46370665, ...,  2.64375035,
         1.80741646,  0.75709877],
       [ 1.15475266,  0.30545828,  1.15352976, ...,  0.5278407 ,
         0.26594158, -0.2843956 ],
       ...,
       [-0.61453079,  0.81308696, -0.56812455, ..., -0.10390947,
        -1.12154294,  0.51916651],
       [-0.78976333, -0.47021733, -0.77652456, ..., -0.78674374,
        -0.50401019, -0.15839965],
       [ 0.56970207, -0.12389122,  0.66221343, ...,  0.86336352,
        -0.21174278,  1.21187383]], shape=(455, 30))

In [138]:
y_train

471    B
108    M
516    M
418    B
545    B
      ..
35     M
171    M
382    B
142    B
283    M
Name: diagnosis, Length: 455, dtype: object

#### Label Encoding

In [139]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [140]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,

#### Numpy arrays to pytorch tensors

In [164]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [142]:
X_train_tensor.shape,X_test_tensor.shape

(torch.Size([455, 30]), torch.Size([114, 30]))

In [143]:
y_train_tensor.shape,y_test_tensor.shape

(torch.Size([455]), torch.Size([114]))

In [144]:
X_train_tensor[0],X_train_tensor[0].shape,X_train_tensor[0].ndim

(tensor([-0.6174,  2.0988, -0.6459, -0.5966, -0.6579, -0.8415, -0.8157, -0.6664,
          0.1371, -0.8166,  0.6813,  2.6117,  0.5791,  0.0796,  0.1483, -0.5389,
         -0.5484, -0.0049, -0.0205,  0.0261, -0.5777,  1.2538, -0.6186, -0.5660,
         -1.2355, -0.9688, -1.0229, -0.9160, -0.7868, -0.9463],
        dtype=torch.float64),
 torch.Size([30]),
 1)

In [145]:
y_train_tensor[0],y_train_tensor[0].shape,y_train_tensor[0].ndim

(tensor(0), torch.Size([]), 0)

In [146]:
X_train_tensor.shape,X_train_tensor.shape[1]

(torch.Size([455, 30]), 30)

### Defining the model

In [54]:
class MyNN:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss


##### Important hyperparameters

In [78]:
learning_rate = 0.01
epochs = 25

##### Training pipeline

In [81]:
# create the model instance
model = MyNN(X_train_tensor)

# Define loop

for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)


    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)
    

    # backward pass
    loss.backward()

    # parameters(trainable) update
    # During weights' update , we don't need to track the gradients
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    # zero gradients(to prevent accumulation of gradients)
    model.weights.grad.zero_()
    model.weights.grad.zero_()


    # print loss in each epoch
    print(f"Epoch {epoch + 1}, loss: {loss.item()}")


Epoch 1, loss: 3.5709709123925704
Epoch 2, loss: 3.5580509282179875
Epoch 3, loss: 3.54514053903527
Epoch 4, loss: 3.5322399369195367
Epoch 5, loss: 3.51934931731922
Epoch 6, loss: 3.50646887900508
Epoch 7, loss: 3.4935780348832615
Epoch 8, loss: 3.4804982809921805
Epoch 9, loss: 3.467429833215738
Epoch 10, loss: 3.454372900548951
Epoch 11, loss: 3.4413276945169744
Epoch 12, loss: 3.4282944290445974
Epoch 13, loss: 3.415273320378298
Epoch 14, loss: 3.402264586955267
Epoch 15, loss: 3.3892684493006513
Epoch 16, loss: 3.3762851299096366
Epoch 17, loss: 3.3633148531199657
Epoch 18, loss: 3.3503578449865583
Epoch 19, loss: 3.337359804976311
Epoch 20, loss: 3.324232990365732
Epoch 21, loss: 3.31112043339659
Epoch 22, loss: 3.2980223575950456
Epoch 23, loss: 3.284938987117219
Epoch 24, loss: 3.271870546650704
Epoch 25, loss: 3.2588172612792485


In [86]:
model.weights.shape

torch.Size([30, 1])

In [87]:
model.weights

tensor([[0.3348],
        [0.4678],
        [0.1111],
        [0.8458],
        [0.4072],
        [0.3937],
        [0.6572],
        [0.0261],
        [0.8801],
        [0.7946],
        [0.2828],
        [0.0316],
        [0.2839],
        [0.2370],
        [0.3112],
        [0.7997],
        [0.0449],
        [0.5015],
        [0.7337],
        [0.6357],
        [0.9148],
        [0.7320],
        [0.5581],
        [0.4443],
        [0.2479],
        [0.3308],
        [0.3874],
        [0.2164],
        [0.6453],
        [0.3429]], dtype=torch.float64, requires_grad=True)

In [88]:
model.bias

tensor([0.0254], dtype=torch.float64, requires_grad=True)

#### Evaluation

In [106]:

# Since this is for inference,
# We don't keep track of gradients here (weights are involved in this calculation, that's why switching off gradient tracking)
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()

    
accuracy = (y_pred==y_test_tensor).float().mean()
print(f"accuracy:{accuracy}")

    

accuracy:0.5438596606254578


#### Redefining the model (simplified implementation)

In [168]:
import torch.nn as nn

In [170]:
class MyNN(nn.Module):

    def __init__(self,n_features):
        super().__init__()
        self.linear = nn.Linear(n_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


In [171]:
X_train_tensor.shape,y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

##### Why Use .unsqueeze() in Binary Classification?
Shape Mismatch:

The output of your model (y_pred) has a shape of [N, 1], where N is the batch size.

However, your target tensor (y_train_tensor) might have a shape of [N].

nn.BCELoss expects both tensors to have the same shape, so the target tensor needs to be reshaped to [N, 1].

In [ ]:
# Hyperparameters
learning_rate = 0.01
epochs = 25


# Define the loss function
loss_function = nn.BCELoss()

# Ensure data tensors are in the correct dtype
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

# Create the model
model = MyNN(X_train_tensor.shape[1])

# Define the optimizer (model.parameters() is an iterator that contains the model's parameters)
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

# Training loop
for epoch in range(epochs):
    
    # Forward pass
    y_pred = model(X_train_tensor)

    # Compute the loss
    loss = loss_function(y_pred, y_train_tensor.unsqueeze(1))  # Match shape for BCELoss

    # Zero the gradients to avoid accumulation (before backward pass)
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update parameters
    optimizer.step()

    

    # Print the loss for the epoch
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss.item():.4f}")


Epoch 1/25, Loss: 0.7354
Epoch 2/25, Loss: 0.7145
Epoch 3/25, Loss: 0.6947
Epoch 4/25, Loss: 0.6762
Epoch 5/25, Loss: 0.6588
Epoch 6/25, Loss: 0.6424
Epoch 7/25, Loss: 0.6270
Epoch 8/25, Loss: 0.6125
Epoch 9/25, Loss: 0.5987
Epoch 10/25, Loss: 0.5857
Epoch 11/25, Loss: 0.5735
Epoch 12/25, Loss: 0.5618
Epoch 13/25, Loss: 0.5508
Epoch 14/25, Loss: 0.5403
Epoch 15/25, Loss: 0.5303
Epoch 16/25, Loss: 0.5209
Epoch 17/25, Loss: 0.5118
Epoch 18/25, Loss: 0.5032
Epoch 19/25, Loss: 0.4949
Epoch 20/25, Loss: 0.4871
Epoch 21/25, Loss: 0.4795
Epoch 22/25, Loss: 0.4723
Epoch 23/25, Loss: 0.4654
Epoch 24/25, Loss: 0.4588
Epoch 25/25, Loss: 0.4524


In [180]:
# Ensure tensors are of the same dtype
X_test_tensor = X_test_tensor.float()

# Perform inference
with torch.no_grad():
    y_pred = model(X_test_tensor)  # Call the model directly
    y_pred = (y_pred > 0.5).float()  # Apply threshold

# Calculate accuracy
accuracy = (y_pred == y_test_tensor.unsqueeze(1)).float().mean().item()
print(f"Accuracy: {accuracy:.4f}")


Accuracy: 0.9386
